#!/bin/sh

rate=0.05
for nodes in 1 2 4 8 16 32 64
do
    for j in 1 2 3 4 5
    do
        echo "number of nodes: ${nodes}"
        build/ml -L neuralnet -l ${rate} -m 0.0 -E random .7 -A project-data/iris.arff --add-layer ${nodes} |
                    awk '
/total epoch/ { print $0 }
/Accuracy.*training set/ { print $0 }
/Accuracy.*test set/ { print $0 }
/Set accuracy/ { print $0 }'
    done
done
