Import('debug','commonSourceIncludes')
sources=['DecisionTreeLearner.cpp','DecisionTree.cpp','DTNode.cpp']
library = debug.StaticLibrary('decisiontree', \
    sources, \
    CPPFLAGS = commonSourceIncludes)
